export type Destination = "Alibag" | "Dapoli" | "Karjat";
export type Category = "villa" | "apartment";
export type PoolType = "private" | "infinity" | "clubhouse" | "private+baby" | null;

export interface Property {
  id: number;
  slug: string;
  name: string;
  category: Category;
  location: {
    area: string;
    destination: Destination;
    distanceFromMumbai: string;
  };
  tagline: string;
  description: string;
  bedrooms: number;
  bathrooms: number;
  maxGuests: number;
  pool: {
    hasPool: boolean;
    type: PoolType;
  };
  amenities: string[];
  pricing: {
    weekday: number;
    weekend: number;
    deposit: number;
  };
  images: string[];
  featured: boolean;
}

export const properties: Property[] = [
  {
    id: 20,
    slug: "killa-villa",
    name: "Killa Villa",
    category: "villa",
    location: {
      area: "Varsoli",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Modern glass villa with private pool in Varsoli",
    description:
      "A modern 3BHK private villa in Varsoli, Alibag — featuring full-height glass walls, a double-sized living area, a private swimming pool, and warm interiors. With space for six guests and a caretaker on call, every detail of your stay is taken care of.",
    bedrooms: 3,
    bathrooms: 5,
    maxGuests: 6,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "3 AC Bedrooms",
      "AC Living Room",
      "Smart TV",
      "Wi-Fi",
      "Private Pool",
      "Lawn",
      "Outdoor Games",
      "Board Games",
      "Refrigerator",
      "Microwave",
      "Induction",
      "Dishes & Silverware",
      "5 Bathrooms",
      "Towels & Toiletries",
      "Power Backup",
      "Caretaker",
      "Private Parking",
      "24hr CCTV",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [
      "https://ik.imagekit.io/tnf/Soumil%20Stay/Soumil%20Stay%20Killa/Screenshot%202026-06-01%20at%2008.07.47.png",
    ],
    featured: false,
  },
  {
    id: 1,
    slug: "soumils-2-0",
    name: "Soumils 2.0",
    category: "villa",
    location: {
      area: "Nagaon",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Your private escape in the heart of Nagaon",
    description:
      "A beautifully appointed three-bedroom villa tucked into the quiet lanes of Nagaon, Alibag. Gather your favourite people around the private pool and let the unhurried pace of coastal life do the rest.",
    bedrooms: 3,
    bathrooms: 4,
    maxGuests: 8,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "Private pool",
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Outdoor seating",
      "BBQ area",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 2,
    slug: "soumils-4-0",
    name: "Soumils 4.0",
    category: "villa",
    location: {
      area: "Varsoli",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Two minutes from Varsoli Beach, a world away from everything else",
    description:
      "Set just a two-minute stroll from the golden sands of Varsoli Beach, this three-bedroom villa pairs private-pool luxury with effortless beach access. Salt air, sunsets, and a pool all to yourself — the perfect Alibag formula.",
    bedrooms: 3,
    bathrooms: 4,
    maxGuests: 8,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "Private pool",
      "2 min to Varsoli Beach",
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Outdoor seating",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 3,
    slug: "parambi",
    name: "Parambi",
    category: "villa",
    location: {
      area: "Satghar",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Serene seclusion in Satghar",
    description:
      "Parambi is a calm, graceful retreat nestled in the village of Satghar, Alibag. Three en-suite bedrooms, a sparkling private pool, and an unhurried atmosphere make it ideal for families and close-knit groups seeking genuine rest.",
    bedrooms: 3,
    bathrooms: 4,
    maxGuests: 8,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "Private pool",
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Garden",
      "Outdoor seating",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 4,
    slug: "sea-lestine",
    name: "Sea Lestine",
    category: "villa",
    location: {
      area: "Varsoli",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "3BHK villa with pool, baby pool & lawn, near Varsoli Beach",
    description:
      "Sea Lestine is a 3-bedroom villa in Varsoli, Alibag — just 2 km from Varsoli Beach — featuring a 16×20 ft private pool with a dedicated baby pool section and a connected private lawn. Three fully air-conditioned bedrooms across two floors, a spacious living area, and a caretaker who can arrange home-cooked meals make it an ideal coastal retreat for families and groups.",
    bedrooms: 3,
    bathrooms: 4,
    maxGuests: 8,
    pool: { hasPool: true, type: "private+baby" },
    amenities: [
      "3 AC Bedrooms",
      "1 Bedroom on Ground Floor",
      "2 Bedrooms on First Floor",
      "AC Living Room",
      "Smart TV",
      "Private Pool (16×20 ft)",
      "Baby Pool Section",
      "Private Lawn",
      "Basic Kitchen",
      "Essential Utensils",
      "3 Attached Bathrooms",
      "1 Common Bathroom",
      "Parking (up to 2 Cars)",
      "Caretaker Available",
      "Home-Cooked Meals (on request, extra charges)",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [
      "https://ik.imagekit.io/tnf/Soumil%20Stay/Sea%20Lestine/Screenshot%202026-08-12%20at%2017.49.23.png",
    ],
    featured: false,
  },
  {
    id: 5,
    slug: "suruchi",
    name: "Suruchi",
    category: "villa",
    location: {
      area: "Kurul",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Six bedrooms on the lake — Alibag's most extraordinary address",
    description:
      "Suruchi is our flagship property: a sprawling six-bedroom estate that sits right on the lake's edge in Kurul, Alibag. With a 25×55 ft private pool and gazebo, two spacious living areas, seven bathrooms, and capacity for eighteen guests, it is the definitive venue for milestone celebrations and large family gatherings.",
    bedrooms: 6,
    bathrooms: 7,
    maxGuests: 18,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "6 AC Bedrooms",
      "2 Bedrooms on Ground Floor",
      "4 Bedrooms on First Floor",
      "2 Spacious Living Areas",
      "Smart TV",
      "Private Pool (25×55 ft)",
      "Big Gazebo",
      "Private Lawn",
      "Basic Kitchen",
      "Essential Utensils",
      "6 Attached Bathrooms",
      "1 Common Bathroom",
      "Parking (up to 8 Cars)",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [
      "https://ik.imagekit.io/tnf/Soumil%20Stay/Suruchi%20LQ/UEC44354.jpg?tr=w-1200,q-80,f-auto",
    ],
    featured: true,
  },
  {
    id: 6,
    slug: "athaangg",
    name: "Athaangg",
    category: "villa",
    location: {
      area: "Thal",
      destination: "Alibag",
      distanceFromMumbai: "100 km",
    },
    tagline: "4BHK villa with pool & baby pool, steps from Thal Beach",
    description:
      "Athaangg is a spacious 4-bedroom villa in Thal, Alibag, just 250 metres from Thal Beach. Featuring a 15×22 ft private pool with a dedicated baby pool section, a connected private lawn, and parking for up to 6 cars — a perfect coastal retreat for families and groups.",
    bedrooms: 4,
    bathrooms: 4,
    maxGuests: 10,
    pool: { hasPool: true, type: "private+baby" },
    amenities: [
      "4 AC Bedrooms",
      "3 Ground Floor Bedrooms",
      "1 First Floor Bedroom",
      "5 Beds",
      "AC Living Room",
      "Smart TV",
      "Private Pool (15×22 ft)",
      "Baby Pool Section",
      "Private Lawn",
      "Basic Kitchen",
      "Essential Utensils",
      "4 Bathrooms (All Attached)",
      "Parking (up to 6 Cars)",
      "Caretaker Available",
      "Wi-Fi",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [
      "https://ik.imagekit.io/tnf/Soumil%20Stay/Athaang/Screenshot%202026-08-11%20at%2008.44.51.png",
    ],
    featured: false,
  },
  {
    id: 7,
    slug: "aamrai-vista",
    name: "Aamrai Vista",
    category: "villa",
    location: {
      area: "Varsoli",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "4BHK villa with pool & baby pool, steps from Varsoli Beach",
    description:
      "Aamrai Vista is a spacious 4-bedroom villa in Varsoli, Alibag, just 250 metres from Varsoli Beach. Featuring a 16×22 ft private pool with a dedicated baby pool section, an AC living room, and parking for up to 7 cars — ideal for families and groups seeking a comfortable coastal retreat.",
    bedrooms: 4,
    bathrooms: 5,
    maxGuests: 10,
    pool: { hasPool: true, type: "private+baby" },
    amenities: [
      "4 AC Bedrooms",
      "AC Living Room",
      "Smart TV",
      "Private Pool (16×22 ft)",
      "Baby Pool Section",
      "Private Lawn",
      "Basic Kitchen",
      "Essential Utensils",
      "5 Bathrooms",
      "Parking (up to 7 Cars)",
      "Caretaker Available",
      "Wi-Fi",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [
      "https://ik.imagekit.io/tnf/Soumil%20Stay/Aamrai%20Vista/Screenshot%202026-08-11%20at%2008.24.43.png",
    ],
    featured: false,
  },
  {
    id: 8,
    slug: "wada",
    name: "Wada",
    category: "villa",
    location: {
      area: "Alibag",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Heritage character meets modern Alibag luxury",
    description:
      "Wada draws its name and soul from the grand ancestral wada homes of the Konkan coast, reimagined with every modern comfort. Four bedrooms, a private pool, and generous communal spaces make it perfect for groups that love to gather.",
    bedrooms: 4,
    bathrooms: 4,
    maxGuests: 10,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "Private pool",
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Outdoor seating",
      "Heritage architecture",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 9,
    slug: "grace-casa",
    name: "Grace Casa",
    category: "villa",
    location: {
      area: "Alibag",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Graceful, intimate, and entirely your own",
    description:
      "Grace Casa is a refined three-bedroom retreat that prioritises warmth, comfort, and understated elegance. A private pool and well-appointed interiors create an intimate setting well-suited to couples, small families, or friends travelling together.",
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 8,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "Private pool",
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Outdoor seating",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 10,
    slug: "akshaya-villa",
    name: "Akshaya Villa",
    category: "villa",
    location: {
      area: "Alibag",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "A private jacuzzi villa for the discerning few",
    description:
      "Akshaya Villa elevates the Alibag weekend with a private pool and an in-villa jacuzzi — a rare combination that turns an ordinary getaway into a genuine spa retreat. Two elegant bedrooms and three bathrooms mean comfort is never compromised.",
    bedrooms: 2,
    bathrooms: 3,
    maxGuests: 6,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "Private pool",
      "Jacuzzi",
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Outdoor seating",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 11,
    slug: "loft",
    name: "Loft",
    category: "villa",
    location: {
      area: "Kolthare",
      destination: "Dapoli",
      distanceFromMumbai: "215 km",
    },
    tagline: "Sweeping sea views and a peaceful private retreat in Kolthare",
    description:
      "Loft is a serene 2-bedroom villa in Kolthare, Dapoli, with stunning sea views visible from across the property. Fully air-conditioned throughout — bedrooms and living area — with inverter and generator backup for uninterrupted comfort. A quiet, private setting designed for genuine relaxation. Food is available at a restaurant approximately 1 km from the property.",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    pool: { hasPool: false, type: null },
    amenities: [
      "2 AC Bedrooms",
      "AC Living Area",
      "Stunning Sea View",
      "Inverter Backup",
      "Generator Backup",
      "Private & Peaceful Setting",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [
      "https://ik.imagekit.io/tnf/Soumil%20Stay/Loft%20(Dapoli)/_M027224-HDR.jpg",
    ],
    featured: false,
  },
  {
    id: 12,
    slug: "amoda",
    name: "Amoda",
    category: "villa",
    location: {
      area: "Kolthare",
      destination: "Dapoli",
      distanceFromMumbai: "200 km",
    },
    tagline: "Space, greenery, and the calm of Dapoli's coastline",
    description:
      "Amoda is a generous four-bedroom villa in the coastal village of Kolthare that trades pool for pure, unhurried space — think sprawling interiors, lush surroundings, and the kind of quiet that Dapoli does best. Perfect for large families who prefer natural beauty over poolside bustle.",
    bedrooms: 4,
    bathrooms: 5,
    maxGuests: 10,
    pool: { hasPool: false, type: null },
    amenities: [
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Outdoor seating",
      "Garden",
      "Spacious lawn",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 13,
    slug: "vardaan",
    name: "Vardaan",
    category: "villa",
    location: {
      area: "New Matheran",
      destination: "Karjat",
      distanceFromMumbai: "80 km",
    },
    tagline: "Mountain views, modern design, and a peaceful gated retreat in Karjat",
    description:
      "Vardaan is a thoughtfully designed 2-bedroom villa inside the New Matheran gated community in Karjat. Both bedrooms are air-conditioned with attached washrooms. A large terrace offers panoramic mountain views, surrounded by seasonal waterfalls and trekking trails. The villa has a basic kitchen with an induction cooktop and essential utensils. A local cook can be arranged with advance notice at extra charge — note that the nearest restaurants are 18 km away, so guests are strongly advised to carry groceries and essentials on arrival.",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    pool: { hasPool: false, type: null },
    amenities: [
      "2 AC Bedrooms",
      "Attached Washrooms",
      "AC Living Area",
      "Large Terrace",
      "Panoramic Mountain Views",
      "Basic Kitchen",
      "Induction Cooktop",
      "Essential Utensils",
      "Gated Community",
      "Seasonal Waterfalls Nearby",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [
      "https://ik.imagekit.io/tnf/Soumil%20Stay/Vardaan%20Karjat/24.jpeg",
    ],
    featured: false,
  },
  {
    id: 14,
    slug: "parvata-vista",
    name: "Parvata Vista",
    category: "villa",
    location: {
      area: "New Matheran",
      destination: "Karjat",
      distanceFromMumbai: "80 km",
    },
    tagline: "Mountain air, a private pool, and Karjat at its finest",
    description:
      "Parvata Vista is a secluded two-bedroom villa inside the New Matheran gated community, Karjat — surrounded by Sahyadri peaks, seasonal waterfalls, and complete quiet. A private pool with no usage-time restrictions, two large terraces with panoramic views, and the Bhimashankar Temple trek accessible on foot make it the ideal retreat for those who want to genuinely disconnect.",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 6,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "2 AC Bedrooms",
      "1 Bedroom on Ground Floor",
      "1 Bedroom on First Floor",
      "Attached Washrooms",
      "Spacious Living Area",
      "Two Large Terraces",
      "Panoramic Mountain Views",
      "Private Pool",
      "Basic Kitchen",
      "Induction Cooktop",
      "Essential Utensils",
      "Gated Community (New Matheran)",
      "Seasonal Waterfalls Nearby",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [
      "https://ik.imagekit.io/tnf/Soumil%20Stay/Parvata%20Vista%20LQ/DJI_20250729143745_0127_D%20copy.jpg?tr=w-1200,q-80,f-auto",
    ],
    featured: false,
  },
  {
    id: 15,
    slug: "ritams",
    name: "RiTaMs",
    category: "villa",
    location: {
      area: "Nandgaon",
      destination: "Karjat",
      distanceFromMumbai: "80 km",
    },
    tagline: "Karjat's hidden gem — pools, peaks, and pure peace",
    description:
      "RiTaMs is a charming private-pool villa nestled in the hills of Nandgaon, offering an intimate escape with two bedrooms, three bathrooms, and sweeping views of the Sahyadri range. Quiet, thoughtfully designed, and exactly what a Karjat weekend should feel like.",
    bedrooms: 2,
    bathrooms: 3,
    maxGuests: 6,
    pool: { hasPool: true, type: "private" },
    amenities: [
      "Private pool",
      "Mountain views",
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Outdoor seating",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 16,
    slug: "pinnacle-1",
    name: "Pinnacle 1",
    category: "apartment",
    location: {
      area: "Kihim Beach",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "A stylish beachside apartment steps from Kihim",
    description:
      "Pinnacle 1 is a compact, well-finished one-bedroom apartment in the serene Kihim Beach area of Alibag — ideal for couples or solo travellers seeking a private coastal base without villa-scale logistics. The beach is just a short walk away.",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    pool: { hasPool: false, type: null },
    amenities: [
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Near Kihim Beach",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 17,
    slug: "pinnacle-2",
    name: "Pinnacle 2",
    category: "apartment",
    location: {
      area: "Kihim Beach",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Kihim Beach living, distilled to its essence",
    description:
      "Pinnacle 2 mirrors the calm, clean aesthetic of its sibling unit — a thoughtfully furnished one-bedroom apartment in the Kihim Beach neighbourhood, perfect for a peaceful two-night escape from the city.",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    pool: { hasPool: false, type: null },
    amenities: [
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Near Kihim Beach",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 18,
    slug: "pinnacle-3",
    name: "Pinnacle 3",
    category: "apartment",
    location: {
      area: "Sainagar Kihim",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Quiet coastal living in Sainagar Kihim",
    description:
      "Nestled in the peaceful locality of Sainagar Kihim, Pinnacle 3 offers a private, well-appointed one-bedroom apartment that lets you experience Alibag at a gentler, more intimate pace. Simple, stylish, and everything you need.",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    pool: { hasPool: false, type: null },
    amenities: [
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Quiet neighbourhood",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 19,
    slug: "pinnacle-4",
    name: "Pinnacle 4",
    category: "apartment",
    location: {
      area: "Sainagar Kihim",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "Your private corner of Sainagar Kihim",
    description:
      "Pinnacle 4 rounds out the Pinnacle collection with the same clean, comfortable one-bedroom layout in Sainagar Kihim — a great choice for anyone wanting a fuss-free Alibag weekend that is entirely their own.",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    pool: { hasPool: false, type: null },
    amenities: [
      "Fully equipped kitchen",
      "Air conditioning",
      "Wi-Fi",
      "Parking",
      "Quiet neighbourhood",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [],
    featured: false,
  },
  {
    id: 21,
    slug: "cherry",
    name: "Cherry",
    category: "apartment",
    location: {
      area: "Alibag",
      destination: "Alibag",
      distanceFromMumbai: "95 km",
    },
    tagline: "3BHK air-conditioned apartment, steps from Alibag Beach",
    description:
      "Cherry is a spacious first-floor apartment in the heart of Alibag — just 500 m from Alibag Bus Stand and 1 km from Alibag Beach. Three fully air-conditioned bedrooms, a comfortable living area, and a caretaker who can arrange home-cooked meals make it an ideal base for families and groups exploring the Alibag coastline.",
    bedrooms: 3,
    bathrooms: 4,
    maxGuests: 6,
    pool: { hasPool: false, type: null },
    amenities: [
      "3 AC Bedrooms",
      "AC Living Room",
      "Smart TV",
      "Wi-Fi",
      "Basic Kitchen",
      "Essential Utensils",
      "4 Bathrooms (3 Attached + 1 Common)",
      "Open Parking",
      "Caretaker Available",
      "Home-Cooked Meals (on request, extra charges)",
    ],
    pricing: { weekday: 0, weekend: 0, deposit: 0 },
    images: [
      "https://ik.imagekit.io/tnf/Soumil%20Stay/Cherrys/_M027373-HDR.jpg",
    ],
    featured: false,
  },
];

export const villas = properties.filter((p) => p.category === "villa");
export const apartments = properties.filter((p) => p.category === "apartment");
export const featuredProperty = properties.find((p) => p.featured) ?? properties[0];

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}

export function getPropertiesByDestination(destination: Destination): Property[] {
  return properties.filter((p) => p.location.destination === destination);
}
